#!/bin/bash

if [ $# -lt 2 ];then
    echo "Need 2 parameters! <bedgraph> <chrom info> <out>"
    exit
fi


F=$1
G=$2
out=$3

bedClip ${F} ${G} ${F}.clip

bedGraphToBigWig ${F}.clip ${G} ${out}

rm -f ${F}.clip

