#!/bin/bash -ex
# Run bash with -e exit on first error

rawbam=$1
finalbam=$2
mapthresh=$3 ## we prefer 1
qc=$4
bamwithoutchrm=$5

samtools view -F 1804 -q ${mapthresh} -b ${rawbam} > ${finalbam}
samtools flagstat ${finalbam} > ${qc}

## utilize UCSC utility for filtering chrM sequences and sponge sequences
edwBamFilter -sponge -chrom=chrM ${finalbam} ${bamwithoutchrm}  ## qc based on bam without chrm

