#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Using $1 as an index, align paired reads from $2 and $3 to output in $4

threads=$1
index=$2
pair1=$3
pair2=$4
rawbam=$5
qc=$6
prefix=$7

bwa aln -q 5 -l 32 -k 2 -t $threads $index $pair1 > ${pair1}.sai
bwa aln -q 5 -l 32 -k 2 -t $threads $index $pair2 > ${pair2}.sai

bwa sampe $index ${pair1}.sai ${pair2}.sai ${pair1} ${pair2} | samtools view -Shu | samtools sort - ${prefix}
samtools flagstat ${rawbam} >${qc}

rm ${pair1}.sai ${pair2}.sai


