#!/bin/bash
## TODO: use bedops --range -m - to replace awk, input bed.starch generated by tags.sh

## unstarch NHDF_Ad.DNase_seq.hg19.bed.starch | bedops --range 2 -m - | head
testfunc () { echo "$# parameters"; echo "$@"; }

if [ $# -lt 3 ];then
    echo `basename $0` "<genome> <file-1> <file-2> ... "
    exit
fi

genome=$1

echo ${@:2}

for i in ${@:2}
do
   awk '{if (and($1, 0) == 0) {print $2"\t"$3-3"\t"$3+3"\t"$4} else {print $2"\t"$3-3"\t"$3+3"\t"$4}}' $i > ${i}.5bp
   ln -fs $genome . && fastaFromBed -fi `basename $genome` -bed ${i}.6bp -fo ${i}.fa.tab -tab
   grep -v -i N  ${i}.fa.tab | awk '{sequence[toupper($2)]+=1} END {for (i in sequence) print i"\t"sequence[i]}' | sort -k1d  > ${i}.bias
done